apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
        - name: simple-web
          image: simple-web:1.0
          volumeMounts:
            - name: app-log-vol
              mountPath: /app/logs
      volumes:
        - name: app-log-vol
          emptyDir: {}
